CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "Blogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "Title" character varying(250) NOT NULL,
        "Summary" character varying(500),
        "Content" text,
        "ImageUrl" character varying(500),
        "Author" character varying(100),
        "CreatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Blogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "ContactRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "FullName" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Message" text,
        "Status" character varying(50) NOT NULL DEFAULT 'New',
        "CreatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ContactRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "Instructors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "FullName" character varying(100) NOT NULL,
        "Role" character varying(100),
        "Bio" text,
        "AvatarUrl" character varying(500),
        "Rating" numeric(3,2) NOT NULL DEFAULT 5.0,
        "Experience" character varying(50),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Instructors" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "Subjects" (
        "subjectId" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "subjectName" character varying(150) NOT NULL,
        description character varying(500),
        "imageUrl" character varying(500),
        "isActive" boolean NOT NULL DEFAULT TRUE,
        "createdAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "updatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Subjects" PRIMARY KEY ("subjectId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "Testimonials" (
        "testimonialId" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "studentName" character varying(255) NOT NULL,
        "jobTitle" character varying(255),
        content text NOT NULL,
        rating integer NOT NULL DEFAULT 5,
        "avatarURL" character varying(500),
        "isActive" boolean NOT NULL DEFAULT TRUE,
        "createdAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Testimonials" PRIMARY KEY ("testimonialId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "Users" (
        "userId" integer GENERATED BY DEFAULT AS IDENTITY,
        "fullName" character varying(255) NOT NULL,
        email character varying(255),
        phone character varying(20) NOT NULL,
        "passwordHash" character varying(500) NOT NULL,
        "avatarURL" character varying(500),
        status character varying(50) NOT NULL DEFAULT 'Active',
        "createdAt" timestamp without time zone,
        "updatedAt" timestamp without time zone,
        "LastLoginAt" timestamp without time zone,
        CONSTRAINT "PK_Users" PRIMARY KEY ("userId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "Courses" (
        "courseId" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "courseName" character varying(255) NOT NULL,
        description text,
        "subjectId" integer,
        "instructorId" integer,
        price numeric(18,2),
        "createdAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "updatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Courses" PRIMARY KEY ("courseId"),
        CONSTRAINT "FK_Courses_Instructors_instructorId" FOREIGN KEY ("instructorId") REFERENCES "Instructors" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Courses_Subjects_subjectId" FOREIGN KEY ("subjectId") REFERENCES "Subjects" ("subjectId") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "CourseRegistrations" (
        "registrationId" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "fullName" character varying(255) NOT NULL,
        email character varying(255),
        phone character varying(20) NOT NULL,
        "courseId" integer NOT NULL,
        status character varying(50) NOT NULL DEFAULT 'Mới',
        "createdAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_CourseRegistrations" PRIMARY KEY ("registrationId"),
        CONSTRAINT "FK_Registration_Course" FOREIGN KEY ("courseId") REFERENCES "Courses" ("courseId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "TeachingClasses" (
        "classId" integer GENERATED BY DEFAULT AS IDENTITY,
        "hashCode" character varying(128),
        "className" character varying(255) NOT NULL,
        "courseId" integer NOT NULL,
        "subjectId" integer,
        "instructorId" integer,
        "startDate" timestamp without time zone NOT NULL,
        "endDate" timestamp without time zone NOT NULL,
        status character varying(50) NOT NULL DEFAULT 'Active',
        note character varying(500),
        "createdAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "updatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_TeachingClasses" PRIMARY KEY ("classId"),
        CONSTRAINT "FK_TeachingClasses_Courses_courseId" FOREIGN KEY ("courseId") REFERENCES "Courses" ("courseId") ON DELETE CASCADE,
        CONSTRAINT "FK_TeachingClasses_Instructors_instructorId" FOREIGN KEY ("instructorId") REFERENCES "Instructors" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_TeachingClasses_Subjects_subjectId" FOREIGN KEY ("subjectId") REFERENCES "Subjects" ("subjectId") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE TABLE "TeachingClassStudents" (
        "classId" integer NOT NULL,
        "registrationId" integer NOT NULL,
        "createdAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_TeachingClassStudents" PRIMARY KEY ("classId", "registrationId"),
        CONSTRAINT "FK_TeachingClassStudents_CourseRegistrations_registrationId" FOREIGN KEY ("registrationId") REFERENCES "CourseRegistrations" ("registrationId"),
        CONSTRAINT "FK_TeachingClassStudents_TeachingClasses_classId" FOREIGN KEY ("classId") REFERENCES "TeachingClasses" ("classId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    INSERT INTO "Subjects" ("subjectId", "createdAt", description, "hashCode", "imageUrl", "isActive", "subjectName", "updatedAt")
    VALUES (1, TIMESTAMP '2026-01-01T00:00:00', 'Các khóa học tiếng Anh', NULL, NULL, TRUE, 'Tiếng Anh', TIMESTAMP '2026-01-01T00:00:00');
    INSERT INTO "Subjects" ("subjectId", "createdAt", description, "hashCode", "imageUrl", "isActive", "subjectName", "updatedAt")
    VALUES (2, TIMESTAMP '2026-01-01T00:00:00', 'Các khóa học toán học', NULL, NULL, TRUE, 'Toán', TIMESTAMP '2026-01-01T00:00:00');
    INSERT INTO "Subjects" ("subjectId", "createdAt", description, "hashCode", "imageUrl", "isActive", "subjectName", "updatedAt")
    VALUES (3, TIMESTAMP '2026-01-01T00:00:00', 'Các khóa học vật lý', NULL, NULL, TRUE, 'Vật lý', TIMESTAMP '2026-01-01T00:00:00');
    INSERT INTO "Subjects" ("subjectId", "createdAt", description, "hashCode", "imageUrl", "isActive", "subjectName", "updatedAt")
    VALUES (4, TIMESTAMP '2026-01-01T00:00:00', 'Các khóa học hóa học', NULL, NULL, TRUE, 'Hóa học', TIMESTAMP '2026-01-01T00:00:00');
    INSERT INTO "Subjects" ("subjectId", "createdAt", description, "hashCode", "imageUrl", "isActive", "subjectName", "updatedAt")
    VALUES (5, TIMESTAMP '2026-01-01T00:00:00', 'Các khóa học ngữ văn', NULL, NULL, TRUE, 'Ngữ văn', TIMESTAMP '2026-01-01T00:00:00');
    INSERT INTO "Subjects" ("subjectId", "createdAt", description, "hashCode", "imageUrl", "isActive", "subjectName", "updatedAt")
    VALUES (6, TIMESTAMP '2026-01-01T00:00:00', 'Các khóa học sinh học', NULL, NULL, TRUE, 'Sinh học', TIMESTAMP '2026-01-01T00:00:00');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_CourseRegistrations_courseId" ON "CourseRegistrations" ("courseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_Courses_instructorId" ON "Courses" ("instructorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_Courses_subjectId" ON "Courses" ("subjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_TeachingClasses_courseId" ON "TeachingClasses" ("courseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_TeachingClasses_instructorId" ON "TeachingClasses" ("instructorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_TeachingClasses_subjectId" ON "TeachingClasses" ("subjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    CREATE INDEX "IX_TeachingClassStudents_registrationId" ON "TeachingClassStudents" ("registrationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Subjects"', 'subjectId'),
        GREATEST(
            (SELECT MAX("subjectId") FROM "Subjects") + 1,
            nextval(pg_get_serial_sequence('"Subjects"', 'subjectId'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260708071632_InitialPostgresCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260708071632_InitialPostgresCreate', '10.0.5');
    END IF;
END $EF$;
COMMIT;

