// <auto-generated />
using LeoEducation.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LeoEducation.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606033000_AddSubjects")]
    partial class AddSubjects
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
